Repository Kernel360/hackerthon5-BabLog, pull requests merged in 2025-05, with the labels that each got.

#5 feat : 회원가입 화면 작성
  bablog-front/src/App.jsx
  bablog-front/src/components/Signup.jsx
  bablog-front/src/main.jsx
  bablog-front/src/styles/Signup.css
Labels: frontend

#8 feat: 상세 페이지 컴포넌트 추가
  bablog-front/src/components/DetailPage.jsx
  bablog-front/src/components/Header.jsx
  bablog-front/src/components/ImageSection.jsx
  bablog-front/src/components/TitleSection.jsx
  bablog-front/src/pages/Detail.jsx
Labels: frontend

#12 refactor: 리뷰 이메일 필드 더미 방식 임시 변경
  bablog-be/src/main/java/kr/bablog/bablogbe/reviews/controller/dto/response/ReviewLookUpWebResponse.java
Labels: backend

#19 feat: 로그인 API 기능
  bablog-be/src/main/java/kr/bablog/bablogbe/users/controller/AuthController.java
  bablog-be/src/main/java/kr/bablog/bablogbe/users/controller/dto/request/UserLoginWebRequest.java
  bablog-be/src/main/java/kr/bablog/bablogbe/users/controller/dto/response/LoginResponse.java
  bablog-be/src/main/java/kr/bablog/bablogbe/users/domain/User.java
  bablog-be/src/main/java/kr/bablog/bablogbe/users/service/UserService.java
  bablog-be/src/main/java/kr/bablog/bablogbe/users/service/errors/UserErrorCode.java
  bablog-be/src/main/java/kr/bablog/bablogbe/users/service/errors/UserErrorType.java
  bablog-be/src/main/java/kr/bablog/bablogbe/users/service/errors/exception/InvalidUserPassword.java
  bablog-be/src/main/java/kr/bablog/bablogbe/users/service/errors/exception/UserNotFoundException.java
  bablog-be/src/main/resources/application.yml
Labels: backend, api
